### ISSUE TITLE
I m read trying to  36 MB File Fails

### ISSUE THREAD

**Issue by atuldeokar** [salsify/jsonstreamingparser#48]
I m read trying to  36 MB File Fails,its taking too much time.
$str = file_get_contents('./JString.json');
$arr = json_decode($str, true); // decode the JSON into an associative array

Fast too much than given code jsonstreamingparser...........

**Comment by gonzofy** [comment]
@atuldeokar I don't understand how this is at all related to the json streaming parser.. json_decode is not using the jsonstreamingparser.

**Comment by atuldeokar** [comment]
Thanks for reply .... I tried jsonstreamingparser for reading json file which size is 36 MB its taking too much time instead of that  file_get_contents working fast...

**Comment by gonzofy** [comment]
@atuldeokar I've done much bigger files in less than a minute. I have no idea how you're using the parser, but 36M is not very big, so the issue is very likely how you're using the library.

My guess is that you're using the parser to load the whole file into memory (for example, into a variable like $arr in your example), which is NOT how it should be used; you should parse individual elements of it and then discard them. Please read how to use an e.g. SAX parser and this will make more sense.

**Comment by atuldeokar** [comment]
Thanks Again ....
require_once dirname(__FILE__) . '/../vendor/autoload.php';

$testfile = dirname(__FILE__) . '/../tests/data/JString.json';

$listener = new \JsonStreamingParser\Listener\InMemoryListener();
$stream = fopen($testfile, 'r');
try {
    $parser = new \JsonStreamingParser\Parser($stream, $listener);
    $parser->parse();
    fclose($stream);
} catch (Exception $e) {
    fclose($stream);
    throw $e;
}
$arr=array();
$finalArr=array();
$arr=$listener->getJson();
Installation using composer .json

**Comment by gonzofy** [comment]
See my previous comment. You're trying to load all of the JSON into a single variable in memory, which is not how this parser is designed to be used. Please read up on streaming parsing.

**Comment by soyuka** [comment]
@atuldeokar use https://github.com/MAXakaWIZARD/JsonCollectionParser and/or read up https://soyuka.me/streaming-big-json-files-the-good-way/ (bit old by now but this is the same as JsonCollectionParser)
